// Server-only. Opens a Postgres pool and reads capture files off disk; see
// web/lib/queue.ts on why `server-only` is deliberately not a dependency.
import { getDb, openQueue } from 'assay/store';
import * as schema from 'assay/engine/store/schema';
import { assessField, knownFields } from 'assay/engine/health/observe';
import type { FragilityGrade, DriftState } from 'assay/engine/health/index';
import { asc, desc, eq, inArray } from 'drizzle-orm';

/**
 * What each field looks like when it is right, and how reliably it has been
 * there.
 *
 * The `how it is found` sentence is `src/health`'s own note, not a rewrite of
 * it: it names the anchors holding the field up and how often they have moved.
 * A model never writes this column -- a fluent narrator would eventually
 * produce a reason that contradicts the evidence, and the reader would believe
 * the fluent one.
 */

export const FIELD_FILTERS = ['all', 'held', 'fragile'] as const;
export type FieldFilter = (typeof FIELD_FILTERS)[number];

export interface FieldRow {
  targetId: string;
  scraper: string;
  field: string;
  /** Runs that published a value, out of runs that happened. */
  seen: number;
  runs: number;
  /** The health module's own sentence. Null when it could not be assessed. */
  how: string | null;
  /**
   * What would fix it, read off the anchors the grade was computed from.
   * Null where there is nothing to suggest -- a sturdy field, or one the
   * store could not assess.
   */
  suggestion: string | null;
  grade: FragilityGrade | null;
  drift: DriftState | null;
  /** Open queue items on this field. Held, and still waiting on someone. */
  held: number;
  /** When the published value last differed. Null if it never has. */
  lastChange: Date | null;
  /** Runs the grade could not see -- captures pruned, or never kept. */
  unobserved: number;
}

export interface FieldsView {
  rows: FieldRow[];
  tracked: number;
  fragile: number;
  /** Fields the schema promises that have never once arrived. */
  missing: number;
  heldTotal: number;
}

/**
 * The most recent run whose published value differed from the one before it.
 *
 * Withheld runs are stepped over rather than counted as a change: a hole is
 * not a new value, and calling it one would put "changed today" against a
 * field that published nothing today.
 */
function lastChangeOf(rows: { runId: number; value: string | null; at: Date }[]): Date | null {
  const published = rows.filter((r) => r.value !== null).sort((a, b) => b.runId - a.runId);
  for (let i = 0; i + 1 < published.length; i += 1) {
    if (published[i].value !== published[i + 1].value) return published[i].at;
  }
  return null;
}

/**
 * The engine writes counts as `1 observation(s)`, which is a sentence with the
 * plural left as an exercise for the reader. `src/health` is a data contract
 * shared with the CLI and the API, so the parenthesis is assembled HERE, on the
 * way to the screen, rather than by rewording the engine's note.
 *
 * One rule, applied to every note: `<n> <word>(s)`. That covers `run(s)` and
 * `observation(s)` without this file keeping a list of the words it knows.
 */
const saidPlainly = (note: string) =>
  note.replace(/\b(\d+) ([a-z]+)\(s\)/g, (_m, n: string, word: string) =>
    `${n} ${n === '1' ? word : `${word}s`}`);

/**
 * What to actually do about a grade, derived from the anchors that produced it.
 *
 * Nothing is invented here: `sturdy` means the site wrote an anchor on purpose
 * and it held, so there is nothing to suggest and this says nothing rather than
 * filling the space. `insufficient_history` is not a verdict, so it gets no
 * advice either -- the fix for it is more runs, which is already happening.
 */
function suggest(
  grade: FragilityGrade | null,
  anchors: { key: string; stable: boolean; held: boolean }[],
): string | null {
  /* copy(G) */
  if (grade === 'fragile') {
    return anchors.length === 0
      ? 'Nothing identifies this element but where it sits on the page. A stable id or a data-testid on it would anchor it.'
      : 'Everything holding this up is generated by the build. A stable id or a data-testid on this element would anchor it.';
  }
  if (grade === 'serviceable') {
    return 'It is standing on anchors the site never chose deliberately. An id, a data-testid or a role would survive the next redesign.';
  }
  return null;
}

export async function fieldsView(filter: FieldFilter = 'all'): Promise<FieldsView> {
  const db = getDb();
  const fields = await knownFields();

  const [cells, open] = await Promise.all([
    fields.length
      ? db
          .select({
            targetId: schema.runs.targetId,
            runId: schema.fieldRuns.runId,
            field: schema.fieldRuns.field,
            value: schema.fieldRuns.value,
            proof: schema.fieldRuns.proofId,
            at: schema.runs.startedAt,
          })
          .from(schema.fieldRuns)
          .innerJoin(schema.runs, eq(schema.runs.runId, schema.fieldRuns.runId))
          .where(inArray(schema.runs.targetId, fields.map((f) => f.target)))
          .orderBy(asc(schema.fieldRuns.runId))
      : [],
    openQueue(500),
  ]);

  const waiting = new Set(open.map((q) => q.proofId));

  const rows = await Promise.all(
    fields.map(async (f): Promise<FieldRow> => {
      const mine = cells.filter((c) => c.targetId === f.target && c.field === f.field);
      // Assessing re-parses up to 30 stored pages, so one field failing --
      // a pruned capture, a target that has since been reset -- must not take
      // the whole table down with it. It becomes an absence, not an error.
      let how: string | null = null;
      let suggestion: string | null = null;
      let grade: FragilityGrade | null = null;
      let drift: DriftState | null = null;
      let unobserved = 0;
      try {
        const h = await assessField(f.target, f.field);
        how = saidPlainly(h.fragility.note);
        grade = h.fragility_grade;
        suggestion = suggest(grade, h.fragility.anchors);
        drift = h.drift_state;
        unobserved = h.unobserved_runs;
      } catch {
        how = null;
      }

      return {
        targetId: f.target,
        scraper: f.target.split('__')[0],
        field: f.field,
        seen: mine.filter((c) => c.value !== null).length,
        runs: mine.length,
        how,
        suggestion,
        grade,
        drift,
        held: mine.filter((c) => waiting.has(c.proof)).length,
        lastChange: lastChangeOf(mine.map((c) => ({ runId: c.runId, value: c.value, at: c.at as Date }))),
        unobserved,
      };
    }),
  );

  const keep =
    filter === 'held'
      ? rows.filter((r) => r.held > 0)
      : filter === 'fragile'
        ? rows.filter((r) => r.grade === 'fragile')
        : rows;

  return {
    rows: keep,
    tracked: rows.length,
    fragile: rows.filter((r) => r.grade === 'fragile').length,
    missing: rows.filter((r) => r.seen === 0 && r.runs > 0).length,
    heldTotal: rows.reduce((n, r) => n + r.held, 0),
  };
}

/**
 * One published cell, over time, for one target.
 *
 * `value: null` is the hole and it is NOT a missing lookup -- a held cell is a
 * cell the gate declined to publish, and the row exists precisely to say so.
 * The status and the reason code come along so the screen can name which
 * refusal it was; nothing here fills the gap with a guess or drops the row.
 */
export interface FieldValue {
  runId: number;
  at: Date | null;
  field: string;
  value: string | null;
  /** `live | healed | quarantined | stale | degraded`, the store's own word. */
  status: string;
  reason: string | null;
  proof: string;
}

export interface TargetHistory {
  targetId: string;
  scraper: string;
  rows: FieldValue[];
}

/**
 * The last `limit` cells this target published or withheld, newest first.
 *
 * A target row is one field (`{slug}__{field}`), so in practice this is one
 * field's history -- but `field_runs` is keyed by run AND field, so the column
 * is read rather than assumed. A target that grows a second field starts
 * showing it here on the day it does.
 */
export async function targetHistory(targetId: string, limit = 30): Promise<TargetHistory> {
  const rows = await getDb()
    .select({
      runId: schema.fieldRuns.runId,
      at: schema.runs.startedAt,
      field: schema.fieldRuns.field,
      value: schema.fieldRuns.value,
      status: schema.fieldRuns.status,
      reason: schema.fieldRuns.reason,
      proof: schema.fieldRuns.proofId,
    })
    .from(schema.fieldRuns)
    .innerJoin(schema.runs, eq(schema.runs.runId, schema.fieldRuns.runId))
    .where(eq(schema.runs.targetId, targetId))
    .orderBy(desc(schema.fieldRuns.runId))
    .limit(limit);

  return {
    targetId,
    scraper: targetId.split('__')[0] ?? targetId,
    rows: rows.map((r) => ({ ...r, at: (r.at as Date | null) ?? null, reason: r.reason ?? null })),
  };
}
