#!/usr/bin/env node
// Read the design tokens out of Figma and write them into the app as CSS.
//
// Figma's Variables REST API is Enterprise-only, so this does not run
// unattended -- it prints a plugin script you paste into the Figma console
// (or hand to an agent with Figma MCP access), then consumes the JSON that
// comes back. That is the same route the design work has used all along.
//
// The OUTPUT is committed. A self-hoster cloning this repo has no Figma
// token and must never need one: `npm install && npm run dev` has to work
// with the tokens already in the tree.
//
//   node tools/tokens.js --print     show the reader script to run in Figma
//   node tools/tokens.js tokens.json write web/app/tokens.css from a dump
//
// ponytail: no Style Dictionary. 23 variables and 20 text styles do not
// justify a build pipeline; swap it in if the token count ever gets away.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'web', 'app', 'tokens.css');

// The script to run inside Figma. Kept here so the reader and the writer
// cannot drift apart -- if the shape changes, both change in one file.
const READER = `
const cols = await figma.variables.getLocalVariableCollectionsAsync();
const col = cols.find(c => c.name === 'assay');
const mode = col.modes[0].modeId;
const hex = c => '#' + [c.r,c.g,c.b].map(v => Math.round(v*255).toString(16).padStart(2,'0')).join('');
const vars: any[] = [];
for (const id of col.variableIds) {
  const v = await figma.variables.getVariableByIdAsync(id);
  if (!v) continue;
  const raw = v.valuesByMode[mode];
  vars.push({ name: v.name, type: v.resolvedType,
              value: v.resolvedType === 'COLOR' ? hex(raw) : raw });
}
const styles = (await figma.getLocalTextStylesAsync()).map(s => ({
  name: s.name, family: s.fontName.family, size: s.fontSize,
  lineHeight: s.lineHeight && s.lineHeight.unit === 'PIXELS' ? s.lineHeight.value : null,
  letterSpacing: s.letterSpacing && s.letterSpacing.value ? s.letterSpacing.value : 0,
}));
const effects = (await figma.getLocalEffectStylesAsync()).map(s => ({
  name: s.name,
  shadows: s.effects.filter(e => e.visible && e.type === 'DROP_SHADOW').map(e => ({
    x: e.offset.x, y: e.offset.y, blur: e.radius, alpha: e.color.a })),
}));
return JSON.stringify({ vars, styles, effects }, null, 2);
`.trim();

/** `accent/brand` -> `--accent-brand`. Slashes are the only separator Figma uses. */
const cssName = (n: any) => '--' + n.replace(/\//g, '-').replace(/\./g, '_');

function emit({ vars, styles, effects }: any) {
  const colors = vars.filter((v: any) => v.type === 'COLOR');
  const numbers = vars.filter((v: any) => v.type !== 'COLOR');
  const L: any[] = [];

  L.push('/* Generated by tools/tokens.js from Figma file FYnhhLeMulixqTTyjP7gJd.');
  L.push(' * Do not edit by hand -- change the variable in Figma and regenerate:');
  L.push(' *   node tools/tokens.js --print   # run the printed script in Figma');
  L.push(' *   node tools/tokens.js dump.json # write this file from the result');
  L.push(` * ${colors.length} colours, ${numbers.length} numbers, ${styles.length} text styles.`);
  L.push(' */');
  L.push('');
  // `static` matters: a plain @theme is tree-shaken, so a token nothing
  // references yet is silently dropped from the build. These are a design
  // system, not a utility set -- every one has to survive to the stylesheet
  // whether a component uses it today or not.
  L.push('@theme static {');

  L.push('  /* colour */');
  for (const c of colors) L.push(`  ${cssName(c.name)}: ${c.value};`);

  L.push('');
  L.push('  /* geometry */');
  for (const n of numbers) L.push(`  ${cssName(n.name)}: ${n.value}px;`);

  L.push('');
  L.push('  /* type -- Questrial ships ONE weight, so hierarchy is size,');
  L.push('     colour and caps-with-tracking. Never font-weight. */');
  L.push("  --font-sans: var(--font-questrial), ui-sans-serif, system-ui, sans-serif;");
  L.push("  --font-mono: var(--font-roboto-mono), ui-monospace, SFMono-Regular, monospace;");
  for (const s of styles) {
    L.push(`  --text-${s.name.replace(/\//g, '-').replace(/\./g, '_')}: ${s.size}px;`);
  }

  L.push('');
  L.push('  /* elevation */');
  for (const e of effects) {
    const v = e.shadows
      .map((s: any) => `${s.x}px ${s.y}px ${s.blur}px rgb(0 0 0 / ${s.alpha})`)
      .join(', ');
    L.push(`  --shadow-${e.name.replace(/\//g, '-')}: ${v};`);
  }
  L.push('}');
  L.push('');

  // Text styles carry line-height and tracking that a bare size loses.
  // One utility class per Figma style keeps the mapping honest and greppable.
  L.push('/* One class per Figma text style. Named by role, not by size, so a');
  L.push('   size change in Figma does not rename anything in the app. */');
  for (const s of styles) {
    const cls = '.' + s.name.replace(/\//g, '-').replace(/\./g, '_');
    const mono = s.family === 'Roboto Mono';
    const parts = [
      `font-family: var(${mono ? '--font-mono' : '--font-sans'});`,
      `font-size: ${s.size}px;`,
    ];
    // Figma's AUTO line height is the font's own metrics, which is exactly what
    // CSS `normal` means -- so it has to be written down, not left out. Tailwind's
    // preflight sets line-height 1.5 on the root, so an omitted line-height is
    // not the browser default: display/96 came out at 144px against Figma's 99.
    parts.push(s.lineHeight ? `line-height: ${s.lineHeight}px;` : 'line-height: normal;');
    if (s.letterSpacing) parts.push(`letter-spacing: ${round(s.letterSpacing)}px;`);
    L.push(`${cls} { ${parts.join(' ')} }`);
  }
  L.push('');
  return L.join('\n');
}

const round = (n: any) => Math.round(n * 100) / 100;

const arg = process.argv[2];
if (!arg || arg === '--print') {
  console.log('# Run this inside Figma (plugin console or an agent with Figma MCP),');
  console.log('# save the JSON it returns, then: node tools/tokens.js dump.json\n');
  console.log(READER);
  process.exit(0);
}

const dump = JSON.parse(readFileSync(arg, 'utf8'));
writeFileSync(OUT, emit(dump));
console.log(
  `wrote ${OUT}\n  ${dump.vars.length} variables, ${dump.styles.length} text styles, ${dump.effects.length} effect styles`,
);
